sudo: false
language: node_js
node_js:
  - stable
install:
  - npm install
notifications:
  email: false
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
cache:
  npm: false
script:
  - 'npm run test'
after_success:
  - 'npm run coveralls'
