module.exports = {
  up: async (queryInterface) => queryInterface.bulkInsert('Users', [{
    id: 1,
    username: 'Admin',
    email: 'admin@techblogs.pro',
    password: '$2a$10$lcxSe7LrBP4iLNbMwFRB8u6PPdJ3goKApqy7wWUwA8DMlLo4Hwbpq',
    firstName: 'John',
    lastName: 'Doe',
    role: 'Admin',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    username: 'Creator',
    email: 'creator@techblogs.pro',
    password: '$2a$10$drNdmHXsJhrNRNGmIJQZPOfRqHOsvRXwByP.xoS5d2m7KXaQwbvbG',
    firstName: 'Jane',
    lastName: 'Doe',
    role: 'creator',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    username: 'User',
    email: 'user@techblogs.pro',
    password: '$2a$10$Jf8EneOTtWsDOQaxk4dE8ue71mYCp4jSwl4KBzoI6AAdjvn6Tls3y',
    firstName: 'Jace',
    lastName: 'Doe',
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  }]),

  down: async (queryInterface) => queryInterface.bulkDelete('Users', null, {}),
};
